url: "www.lingdeqin.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Zero" # the name of your site, e.g. ACME Corp.

paginate: 10

plugins: [jekyll-paginate]

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  #syntax_highlighter: rouge
